`try` - ключевое слово для блока кода в котором может возникнуть исключение
`except` - ключевое слово для обработки самого исключения

```python
try:
    file = open('file2.txt') # такого файла нет, возникнет исключение
    print(file.readlines())
    file.close()
except FileNotFoundError: # обработка исключения
    print('Файл не найден!')
```

`finally` - ключевое слово для выполнения блока кода в любом случае независимо от того было ли исключение или нет.

```python
try:
    file = open('file.txt') # файл есть, исключения нет
    try:
        r = file.read()
        int(r) # ошибка чтения
        print(r)
    finally: # выполняется в любом случае
        file.close()
except FileNotFoundError:
    print('Файл не найден')
except: # обработка вложенного исключения
    print('Ошибка при чтении файла') # выведет в консоль
```

`with` - обрабатывает исключение и автоматически закрывает файл

```python
try:
    with open('file.txt') as file:
        r = file.read()
        int(r)
        print(r)
except:
    print('Ошибка')
finally:
    print(file.closed)
```